kind: pipeline
name: default

steps:
  - name: test
    image: python:3.6-alpine
    commands:
      - pip install -r requirements.txt
      - pytest -v

  - name: build
    image: python:3.6-alpine
    commands:
      - rm -f reference.json
      - rm -f reference.json.gz
      - python scripts/build.py src -V $TRAVIS_TAG
      - gzip reference.json

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GITHUB_TOKEN
        files: reference.json.gz
      when:
        event:
          - tag
