language: python
sudo: false
python: '3.6'
cache:
  pip: true
  apt: true
install:
- pip install -r requirements.txt
script:
- pytest -v
after_success:
- rm -f reference.json
- rm -f reference.json.gz
- python scripts/build.py src -V $TRAVIS_TAG
- gzip reference.json
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: dFYiUkVu5Ol0SS6xW+5hu/zbUiJLEyOUkUYlKMVg0thKDBWEmbueae5Jb5BLRTykWeCbD/T6uDjtd1czkXYWX1x5xYGHxcIkWlE04ZZ5h5+/kVeO8Ee/SKZ74faqGXxAXnHHzZzk4d+ojQBd+qmwqB/dJGAmvN/7cbaV/O2VhlqmmKoUgHgonIvb3LScvRkBKL7z0Bv5tT0IsFvV5lYKBEPEMszVKPC8gFnJRl5eki4UITrBJogYEwkirf6PU9a51iOyN9CW8GeVtg67RQet6U2rwCrfszKZp/7zn7ZcpPt5zwlm0ZU71yGvnZwxoAZ6/6qXA+fOqo3GouZcBK30cwiooTfvnmhMPbZtQVwF/GCdiL7LSvraMirjazLzu3JW6Yx2K8M4PqmR1rkk5aFMJNA/v8MX9e6y/+Mdnhw4hXxfns/ON8vTR5dsHvZQW7iXpZ5rnv0JbQxHcVwQsC03orI/NYHjA1AbV8EliCymGBKbaVbzDT+QfHp+ss4czMPX2Y5OSGMsfBKX5dhIooU64SRcRfRc8flVff4ymYxOZWFXbL3s8vSsOOgX78/UIQfFqeusHaYi25koxGdR2wqjNJ5lhB02VeLcw6xCDoaWSqzzWMgfyVYqVBZi9EbJ8rXDFUXCQLjDreFjL5xUSq5aF7zLCPuQ97B+qXRf/afESPg=
  file: reference.json.gz
  on:
    tags: true
    repo: virtool/ref-plant-viruses
